# This workflow will install Python dependencies, run tests and lint with a single version of Python
# For more information see: https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-python

name: Python application

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

permissions:
  contents: read

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
    - name: Set up Python 3.10
      uses: actions/setup-python@v3
      with:
        python-version: "3.10"
    # - name: Install dependencies
    #   run: |
    #     python -m pip install --upgrade pip
    #     pip install flake8 pytest
    #     if [ -f requirements.txt ]; then pip install -r requirements.txt; fi
    - name: Get changed files
      id: changed-files
      uses: tj-actions/changed-files@v35
      with:
        write_output_files: true
        json: true
        dir_names: true
        dir_names_max_depth: 2
    - name: echo json
      run: |
        echo all changed_files: ${{ steps.changed-files.outputs.all_changed_files}}
        echo all outputs: ${{ steps.run_tests.outputs.*}}

    - name: Run script
      run: |
        python main.py
